# Generated by Django 3.2.8 on 2021-10-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=200, null=True)),
                ('mobile_number', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
